31 ai pierwsza iteracja
KMRD-Industries/qlp-proto-bindings pull request #9
Opened 2024-12-09 19:27 UTC by Deevo87

Dodane zostało:
- nowe warianty wiadomości dla StateUpdate:
  * MAP_DIMENSIONS_UPDATE - przesyłanie wymiarów mapy,
  * SPAWN_ENEMY_REQUEST - przesyłanie pozycji spawnerów i zapytanie o stworznienie nowych potworów,
  * ENEMY_GOT_HIT_UPDATE - informacja o uderzeniu przeciwnika, zostawiłem to, ale jeszczeni używam
- analogicznie co powyżej nowe typy wiadomości dla StateUpdatu
- dodanie wariantów do MovementUpdatu:
  * PLAYER_MOVEMENT_UPDATE - wszystkie updaty związane z graczem
  * MAP_UPDATE - przesyłanie pozycji przeciwników i graczy potrzebna do aktualizacji algorytmu
- analogicznie dodane są dodatkowe wiadomości do MovementUpdatu
- nowe wiadomości:
  * Enemy - podstawowe informacje potrzebn do stworzenia przeciwnika oraz jego poruszania
  * Obstacle - miejsce, w którym znajduje się kolizja w grze
  * TextureData, ColliosonData - typu wiadomości potrzebne do tworznia przeciwników
  * EnemyGotHitUpdate - zawiera potrzebne informacje do zadania ciosu przeciwnikowi 
  * MapPositionUpdate - aktualizacja pozycji gracza i przeciwników na mapie
  * MapDimensionUpdate - wiadomość do aktulizowania wymiarów mapy

2024-12-14 21:50 UTC, UnluckySiata requested changes
Oprócz kilku rzeczy do poprawy jest ok

2024-12-14 21:50 UTC, UnluckySiata commented on comm.proto
> +    MAP_UPDATE = 1;
0 jest dla proto wartością domyślną i nie powinno być używane jako wariant. Lepiej zacząć od 1 a 0 zostawić dla NONE, wtedy nie ma dziwnych problemów ze źle konstruowanymi
wiadomościami

2024-12-14 21:50 UTC, UnluckySiata commented on .gitignore
Po co takie gitignore? Tego się nigdy nie buduje ręcznie

2024-12-14 21:50 UTC, UnluckySiata commented on comm.proto
Kod poprzesuwany w losowe miejsca, przydałoby się chociaż komentarze usunąć jak nie mają już zastosowania

2024-12-16 21:14 UTC, Deevo87 commented on comm.proto
Sam jesteś w losowe miejsca, od góry masz najważniejsze czyli State i Movement update. Następnie są pod każdą wiadomością są definicje messeges, które są używane w wiadomościach powyżej, takie zchodzenie z hierarchią ważności.

2025-01-02 18:23 UTC, UnluckySiata requested changes
Jest ok tylko wygeneruj pliki korzystając z make, bo są takie jak przed zmianą

2025-01-03 12:16 UTC, UnluckySiata approved these changes

2025-01-03 12:58 UTC, merged